/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_lame_MainActivity */

#ifndef _Included_cn_itcast_lame_MainActivity
#define _Included_cn_itcast_lame_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_lame_MainActivity
 * Method:    convertToMp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_itcast_lame_MainActivity_convertToMp3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_itcast_lame_MainActivity
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_itcast_lame_MainActivity_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
